### ISSUE TITLE
Feature request: ignore newlines

### ISSUE THREAD

**Issue by dreeves** [OneGraph/oneblog#18]
This should probably be rejected on the grounds that it's not the way GitHub renders the gissue text, but in our flavor of markdown, the rendered html ignores newlines.
For example, this sentence is on a new line.
And so is this sentence.
In the GitHub issue, these sentences display on separate lines.
But per the original markdown spec, you need to have two spaces before a newline to make the newline actually show up.
Otherwise it's like html where whitespace between sentences, including newlines, is ignored.

Again, you should probably conform to GitHub's markdown.
It just means that crossposting from our blog to Oneblog is a bit tedious.

(I really like having each sentence on its own line in my source doc. I realize I'm weird.)

So if there were some way to set a flag or something to use other markdown features. Or LaTeX or whoknowswhat, I guess would be the generalization of this feature request. It's a can of worms. You probably really should just close this! :)

**Comment by dwwoelfel** [comment]
Are you sure it doesn't already do that? If I fetch the content of your issue from the API and put it in a oneblog post I see:

![image](https://user-images.githubusercontent.com/476818/99862921-8db8ab00-2b50-11eb-9965-55dcb9a807b3.png)

**Comment by dreeves** [comment]
Ah, well now I feel extremely silly, but I'm almost sure there was _something_ that didn't work right when I pasted in my newline-ridden draft, which led me to painstakingly remove all my newlines.

Stand by while I find repro steps! But if not, this is definitely closable!

PS: I published a new blog post -- https://dreeves.essay.dev/post/21/blog-post-driven-development -- and, whaddyaknow, it's totally fine! So now I think I jumped to the conclusion that this wouldn't work because the GitHub preview and how the GitHub shows the gissue itself preserves those newlines.

So, ironically, probably everyone but me is going to consider the current behavior to be the bug!

**Comment by dwwoelfel** [comment]
If I do end up making newlines work the same as in the gissue, I'll make sure to preserve the current behavior for your site.

**Comment by dreeves** [comment]
That would make me personally happy. I'm not sure you should actually do that though, as I argue in, one sec, let me get it on essay.dev... https://dreeves.essay.dev/post/22/choices-are-bad-the-anti-settings-principle

**Comment by dreeves** [comment]
(Newlines not working in footnotes was another possible reason I jumped to this conclusion and gissued this. But that can be its own gissue if it's important enough.)
