### ISSUE TITLE
No data returned for operation `App_Query`

### ISSUE THREAD

**Issue by hypervillain** [OneGraph/oneblog#6]
Hey guys,

while trying to make changes to the app, I got into this error: `No data returned for operation `App_Query`, got error(s): Unknown error from GitHub.` in PostsRoot component. I thought it came from me moving queries around but checking out to a previous commit didn't help. Its deployed version on Netlify is impacted too: [https://hypervillain-blog.netlify.com](https://hypervillain-blog.netlify.com), so is it possible that the problem is between OneGraph and Github?

Last bit of info, the error source states that `variables: { repoName: null, repoOwner: null }`. I don't know if that helps as preloaded Queries are a complete mystery to me 🤷🏻‍♂️

The current state of the blog is here: [https://github.com/hypervillain/oneblog/tree/master/src](https://github.com/hypervillain/oneblog/tree/master/src). As you can see, I moved the `postsRootQuery` to its own page: [https://github.com/hypervillain/oneblog/blob/master/src/pages/IndexPage.js](https://github.com/hypervillain/oneblog/blob/master/src/pages/IndexPage.js) but reverting this does not seem to help.

Thanks a ton for your help!

**Comment by sgrove** [comment]
Hey @hypervillain - have you successfully deployed the site previously?

If not, would you try deploying OneBlog through OneGraph? It'll automatically set up the Netlify site, GitHub Repo, and set the env vars for you.

<img width="578" alt="Screenshot 2020-03-20 10 06 18" src="https://user-images.githubusercontent.com/35296/77187966-85284600-6a92-11ea-8868-3d23c4ff58a5.png">

Once that's set up, you can hack on the source code and it should just work.


If I misread and you and https://hypervillain-blog.netlify.com was *previously* working let me know!

**Comment by hypervillain** [comment]
Hey @sgrove,

yes it worked yesterday. I may be wrong but I'm also pretty sure that my last push resolved in a working app. I also cloned this repo and copy-pasted my environment variables (that were left untouched across commits) there but had the exact same result. I don't think setting it up via the dashboard would be different but I can happily try anyway

**Comment by hypervillain** [comment]
Ok, new bit of information:

I created a blog from my OG dashboard. I then checked that the build succeeded and I could see a published issue. I then cloned the repository and ran `yarn relay`, which resulted in an error: `Cannot persist query. Missing environment variable 'OG_GITHUB_TOKEN'.`. At this moment, I copy-pasted my env again and got back to the exact same error as I had before. Does it sound familiar?

**Comment by dwwoelfel** [comment]
@hypervillain I think that the problem is that the GitHub token has somehow become invalid.

We sometimes see GitHub revoke the tokens for unknown reasons. If you create a new server-side auth token on the OneGraph dashboard, replace it in your `.env` file, run `yarn relay:clean`, then `yarn relay`, it should work for you again.

Here's what we're working on so that this won't be an issue in the future:
1. Allow re-adding an auth to an existing server-side token (if we had this, you wouldn't have to recreate the relay queries)
2. Auth monitoring, so that you get notified if your token ever expires or is invalidated
3. Better caching, so that your queries can continue to work even if the auth does expire (something kind of similar to [Cloudflare's always online feature](https://www.cloudflare.com/always-online/))
4. Work with GitHub to understand why the tokens become invalid in the first place.

**Comment by hypervillain** [comment]
Thanks for your detailed answer. I could see on my dashboard that the server-side token had somewhat "lost" the Github mention. Unfortunately, creating a new token did not solve the issue. I created a second app, added both GH and persisted query tokens but ended up with a new Relay error: `Error decoding request body: unable to find query with doc_id:...`. This time it's probably me messing up with different configs and repositories. I'll put everything in order tomorrow before going further, to make sure I don't waste your time

**Comment by dwwoelfel** [comment]
> Error decoding request body: unable to find query with doc_id

For that error, my guess is that there is a mismatch between the app_id that persisted the query and the app_id that is making the request. I'll try to get a better error for that case so that it's easier to diagnose.

**Comment by hypervillain** [comment]
That was it indeed. My blog is up and running again. I definitely hope this new token will last a bit longer than the previous one. Can you keep me updated regarding this issue? Out of developer curiosity, I'd love to understand why the tokens become invalid in the first place too.

**Comment by bdougie** [comment]
just spectating here

**Comment by dwwoelfel** [comment]
Circling back to this--we discovered that the reason the tokens become invalid is that we cause GitHub to generate a new token each time you log in and GitHub only allows so many tokens before it starts invalidating old tokens.

We've done two things to mitigate this problem
1. we only keep around a single token for an app and set of scopes. When you log in again, we point the previous logins to the new token.
2. if a token does manage to expire or go bad, we allow you to re-auth with GitHub to refresh the auth on the server-side token on the onegraph dashboard
